sudo: false
dist: trusty
language: node_js
node_js:
- '8'
addons:
  chrome: stable
cache:
  directories:
  - "$HOME/.npm"
env:
  global:
  - JOBS=1
  - secure: iGHPN38Rcsh6Y+W/P7WvKpUJ6XV6xq5bg4M5NHWhntbEu5PRfnJ/8G1Lvi0k+QxB7wFliz29FQGlUO5SiQb0XzgFd3vke8aG3ne2gmO2Jed0tYhpT17VnPBc1y41zDlEOEuUpr8SC2tpjqOyYPNVivP6soQlOzpNXRWWRhlnstfZfCItBPnssU1yuIpqtuDs64Lulm38/wepsm7ISmXue4g6pPTEiGCuXCQaXnDCcG5CKj5fqZWX1kyEOaOE0K9a985fsNmxrDmjwX3tQHFXo0+pgUM04sKon/KGAkx9CzH2Qnilombn1etB3C7utaY4+etQ70ZOsROXV0oe+cN8GoUqEmAoMa4JSBEzyEFUNdarc/vdFx11TuqtPHIT6FfuS2maS0G09C7mIBfAfDll/kpApf6dsooVi42pb2h7Uf68+i1GkPWHaUDzRMGccR/RM0QFhKn/Cmu1lHyF851/+D00AKHQAOt3r/9diqCPM9i0vSLSdigJqERWjlBHOPexA3nWTokZPz08pn7cYGessrSRo004SYliJO9l9knXtqs4uHThS1bj/4kvUNTaHz7wSyXPUOa+CrGcb5Qu5KMeVFyoUlR86f/23ZtWiOzWey8sglmTnqJ/83as7jQ2Qlyqntzg6KkNiCgeAt1S8o8VpBnD+w00pX55/L0gFA2gtAQ=
  matrix:
#  - EMBER_TRY_SCENARIO=ember-lts-2.12
#  - EMBER_TRY_SCENARIO=ember-lts-2.16
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary
  - EMBER_TRY_SCENARIO=ember-default
matrix:
  fast_finish: true
  allow_failures:
  - env: EMBER_TRY_SCENARIO=ember-canary
install:
- yarn install
script:
- yarn lint:js
- node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup
after_success:
  - if [[ ($TRAVIS_BRANCH == master || -n $TRAVIS_TAG) && $EMBER_TRY_SCENARIO == ember-default ]]; then
      node_modules/.bin/ember deploy production;
    fi
packages:
- google-chrome-stable
after_success:
- chmod +x .travis/codecoverage.sh
- if [[ $EMBER_TRY_SCENARIO == 'ember-default' ]]; then .travis/codecoverage.sh; fi
